name: build and test and deploy

permissions:
  contents: write
  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 9.0.x
          
      # Install dotnet wasm buildtools workload
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
        
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm install
        working-directory: src/WebApp/Styles

      # Build CSS (Tailwind or other processors)
      - name: Build CSS with Tailwind
        run: npm run build:css
        working-directory: src/WebApp/Styles
          
      # Publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish ./src/WebApp/WebApp.csproj -c:Release -p:GHPages=true -o dist/Web --nologo
      
      # Commit wwwroot to GitHub Pages
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/Web/wwwroot
